### ISSUE TITLE
0.5.2-rc2: white piece size

### ISSUE THREAD

**Issue by twoplan** [fohristiwhirl/nibbler#22] opened 2019-06-18 14:31 UTC
My config.json

```
"width": 1280,
"height": 760,
"board_size": 520,
"mainline_height": 110,
```

With version 0.5.2-rc2 the white pieces now remain to big in size. The black pieces are scaled correct. Version 0.5.1 was OK.

**Comment by fohristiwhirl** [comment] 2019-06-18 14:47
Can you post a screenshot?

**Comment by fohristiwhirl** [comment] 2019-06-18 14:48
Also, can you confirm that it's always the white pieces, and never the black pieces, even when playing through a game?

**Comment by fohristiwhirl** [comment] 2019-06-18 14:55
Should be fixed now.

**Comment by twoplan** [comment] 2019-06-18 15:30
Thanks, it is fixed ... but Go&Halt don't work any more for me!

**Comment by fohristiwhirl** [comment] 2019-06-18 15:47
Hmm. Does anything show up in the console? (Dev menu --> Toggle Developer Tools --> Console tab).

**Comment by fohristiwhirl** [comment] 2019-06-18 16:07
Also, what's your version of Electron?

**Comment by twoplan** [comment] 2019-06-18 16:19
My console messages.
Nibbler 0.5.1, which works well:
```
fs.js:122 Uncaught Error: EISDIR: illegal operation on a directory, read
    at Object.readSync (fs.js:519)
    at tryReadSync (fs.js:342)
    at Object.readFileSync (fs.js:379)
    at Object.fs.readFileSync (electron/js2c/asar.js:597)
    at Object.renderer.open (9_renderer.js:374)
    at EventEmitter.<anonymous> (9_renderer.js:1231)
    at EventEmitter.emit (events.js:194)
```

Nibbler 0.5.2, where Go&Halt are not working:
```
fs.js:122 Uncaught Error: EISDIR: illegal operation on a directory, read
    at Object.readSync (fs.js:519)
    at tryReadSync (fs.js:342)
    at Object.readFileSync (fs.js:379)
    at Object.fs.readFileSync (electron/js2c/asar.js:597)
    at Object.NewRenderer.renderer.open (95_renderer.js:203)
    at input_loop (99_start.js:109)
```

$ electron -v
v5.0.3

**Comment by fohristiwhirl** [comment] 2019-06-18 16:26
Hmm I suspect that error isn't relevant. I can patch the error (done) but am 99% sure it's unrelated.

**Comment by fohristiwhirl** [comment] 2019-06-18 16:33
OK, I take it back, that's actually the cause. Should be fixed.

**Comment by twoplan** [comment] 2019-06-18 17:35
Well done, all works now like before and the error messages are gone too.

Thanks for sharing your great lc0 gui!

Btw, would it be possible to add an option "go nodes x"? With x=1 we could play a game against the neural network only (without mct-search).

**Comment by fohristiwhirl** [comment] 2019-06-18 17:43
Yes. I'll get on it.

**Closed by fohristiwhirl** 2019-06-18 17:43 UTC
Labels: bug
